// Golden-vector conformance test for the R1 codec seam (subtask 1.0.2.5).
//
// The corpus under tests/fixtures/golden/ is CI-generated by gv_tool
// (tools/golden_vectors/main.cpp, subtask 1.0.2.4) and FROZEN: the .json/.uper
// pairs are verbatim copies of contracts/golden-vectors/. They are a contract,
// not test data of convenience — changing a byte here means re-freezing the
// corpus across every consumer of it, never editing a fixture to make a test
// pass. Nothing in this file may hand-author or regenerate wire bytes.
//
// What is asserted, per case, is the seam in both directions:
//   decode(<case>.uper) == <case>.json   and   encode(<case>.json) == <case>.uper
// The second half is the byte-level freeze: an encoder change that still
// round-trips with itself but shifts an octet is caught here, not in the field.
//
// Seam rule (HLD D3): the codec is a PURE REPRESENTATION TRANSFORM,
// CpmContent ⇄ ASN.1 UPER octets. The JSON fixtures therefore carry wire-native
// integer units and are compared as-is — no unit conversion and no derivation
// happen at this level. F6 confidence conversion, F7 distance derivation and F1
// sender-speed derivation live ABOVE the seam, in the R9 pipeline.

#include "codec/vanetza_cpm_codec.hpp"

#include <cstddef>
#include <cstdint>
#include <fstream>
#include <iterator>
#include <string>
#include <variant>
#include <vector>

#include <gtest/gtest.h>
#include <nlohmann/json.hpp>

namespace {

using v2x::codec::CpmContent;
using v2x::codec::DecodeError;
using v2x::codec::VanetzaCpmCodec;

// One test instance per frozen case, so a failure names the offending vector.
class CpmGoldenVectorTest : public ::testing::TestWithParam<const char*> {
 protected:
  void SetUp() override {
    // A fatal failure here suppresses the test body, so every assertion below
    // may assume both fixtures loaded.
    const std::string stem = std::string(V2X_FIXTURE_DIR) + "/golden/" + GetParam();

    // Binary mode is mandatory: the UPER octets are arbitrary bytes, and any
    // text-mode translation would silently corrupt the frozen vector.
    const std::string uper_path = stem + ".uper";
    std::ifstream uper_in(uper_path, std::ios::binary);
    ASSERT_TRUE(uper_in.is_open()) << "cannot open fixture: " << uper_path;
    const std::string raw((std::istreambuf_iterator<char>(uper_in)),
                          std::istreambuf_iterator<char>());
    ASSERT_FALSE(raw.empty()) << "empty fixture: " << uper_path;
    uper_.assign(raw.begin(), raw.end());

    const std::string json_path = stem + ".json";
    std::ifstream json_in(json_path);
    ASSERT_TRUE(json_in.is_open()) << "cannot open fixture: " << json_path;
    expected_ = nlohmann::json::parse(json_in).get<CpmContent>();
  }

  VanetzaCpmCodec codec_;
  std::vector<std::uint8_t> uper_;
  CpmContent expected_;
};

TEST_P(CpmGoldenVectorTest, DecodeYieldsTheFrozenContent) {
  const auto decoded = codec_.decode(uper_.data(), uper_.size());

  ASSERT_TRUE(std::holds_alternative<CpmContent>(decoded))
      << std::get<DecodeError>(decoded).reason;
  const CpmContent& actual = std::get<CpmContent>(decoded);
  // Dumped as JSON on failure: the seam's own wire shape is the readable diff.
  EXPECT_TRUE(actual == expected_) << "decoded: " << nlohmann::json(actual).dump()
                                   << "\nfixture: " << nlohmann::json(expected_).dump();
}

TEST_P(CpmGoldenVectorTest, EncodeReproducesTheFrozenOctets) {
  const std::vector<std::uint8_t> encoded = codec_.encode(expected_);

  ASSERT_EQ(encoded.size(), uper_.size()) << "encoded length drifted from the frozen vector";
  for (std::size_t i = 0; i < uper_.size(); ++i) {
    // ASSERT stops at the first mismatch, so the reported offset is the first
    // differing octet rather than a wall of every downstream shift.
    ASSERT_EQ(static_cast<unsigned>(encoded[i]), static_cast<unsigned>(uper_[i]))
        << "first differing octet at offset " << i;
  }
}

// gtest test-name suffixes must be alphanumeric/underscore, so the hyphenated
// case names are transliterated rather than falling back to bare indices.
std::string CaseName(const ::testing::TestParamInfo<const char*>& info) {
  std::string name = info.param;
  for (char& ch : name) {
    if (ch == '-') {
      ch = '_';
    }
  }
  return name;
}

INSTANTIATE_TEST_SUITE_P(FrozenCorpus, CpmGoldenVectorTest,
                         ::testing::Values("nominal", "mdt-max", "mdt-min", "conf-unavailable",
                                           "gate-boundary", "coord-large"),
                         CaseName);

}  // namespace
